const $=s=>document.querySelector(s);
let CONFIG={whatsapp:'918416005303'};
fetch('/api/config').then(r=>r.json()).then(c=>{CONFIG=c;setLinks();}).catch(()=>setLinks());
function wa(text){return `https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(text)}`}
function setLinks(){const hello='Hi KPD Delivery! I would like to enquire about a delivery.';['heroWa','contactWa'].forEach(id=>{const e=document.getElementById(id);if(e)e.href=wa(hello)});const p=document.getElementById('partnerWa');if(p)p.href=wa('Hi KPD Delivery! I am interested in partnering with KPD for business deliveries.')}
$('#orderForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();const box=$('#orderResult');box.classList.remove('hidden');if(!r.ok){box.innerHTML=`<b>Could not create order.</b><br>${j.error}`;return}box.innerHTML=`<b>Order created: ${j.orderId}</b><br>Your request is ready. <a target="_blank" href="${j.whatsapp}">Open WhatsApp to send it to KPD →</a><br><span class="small">Save your Order ID to track the delivery later.</span>`;e.target.reset();box.scrollIntoView({behavior:'smooth',block:'center'})});
async function trackOrder(){const id=$('#trackId').value.trim();if(!id)return;const box=$('#trackResult');box.innerHTML='Checking…';const r=await fetch('/api/orders/'+encodeURIComponent(id));const j=await r.json();if(!r.ok){box.innerHTML='<div class="track-result">Order not found. Check the Order ID and try again.</div>';return}box.innerHTML=`<div class="track-result"><b>${j.id}</b> <span class="status">${j.status}</span><p>${j.pickup} → ${j.drop}</p>${j.quote!=null?`<p><b>Confirmed quote: ₹${j.quote}</b></p>`:''}<div class="history">${j.statusHistory.map(x=>`<div class="small">${new Date(x.at).toLocaleString()} — <b>${x.status}</b></div>`).join('')}</div></div>`}
async function postForm(id,url){const f=$(id);f.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();$('#accountResult').innerHTML=r.ok?`Signed in as <b>${j.name}</b>.`:`${j.error||'Something went wrong'}`;if(r.ok)loadOrders()})}
postForm('#registerForm','/api/register');postForm('#loginForm','/api/login');
async function loadOrders(){const r=await fetch('/api/my-orders');if(!r.ok)return;const os=await r.json();const area=$('#ordersArea');area.classList.remove('hidden');area.innerHTML='<h3>My orders</h3>'+ (os.length?os.map(o=>`<div style="padding:12px 0;border-top:1px solid #333"><b>${o.id}</b> · <span class="status">${o.status}</span><br><span class="small">${o.pickup} → ${o.drop}${o.quote!=null?' · ₹'+o.quote:''}</span></div>`).join(''):'<p>No orders yet.</p>')}
loadOrders();
